name: eascheck
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: "^3.7.2"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7
  flutter_signin_button: ^2.0.0
  supabase_flutter: ^2.8.4
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^10.4.0
  camera: ^0.10.0+2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ขึ้นกับว่าต้องการ bundle .env ไหม (flutter_dotenv ไม่ต้องใส่ก็ได้)
  assets:
    - .env

    # เพิ่มโฟลเดอร์รูปทั้งหมด
    - assets/img/
    - assets/icons/ 
    - assets/fonts/





  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700

    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700

    - family: SFProRounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
          weight: 700

